# Generated by Django 4.2.4 on 2023-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_ingredient_image_recipe_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
